apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthcheck
  name: my-healthcheck
  namespace: default
spec:
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 80
    nodePort: 30999
  selector:
    app: healthcheck
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
