apiVersion: v1
kind: ReplicationController
metadata:
  name: my-healthcheck
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.18
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /usr/local/apache2/htdocs
        - name: www-config
          mountPaht: /usr/local/apache2/conf/
      volumes:
      - name: www-data
        hostPath:
          path: /var/www/html
      - name: www-config
        hostPath:
	  path: /var/www/config/healthcheck

