apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: my-www
  namespace: default
spec:
  clusterIP: 10.0.0.236
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: www
  - port: 443
    protocol: TCP
    targetPort: 443
    name: ssl
  selector:
    app: www
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
