apiVersion: v1
kind: ReplicationController
metadata:
  name: my-www
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: myhttpdssl
        image: myhttpdssl
        ports:
        - 
         name: www
         containerPort: 80
        - 
         name: ssl
         containerPort: 443 
        volumeMounts:
        - name: www-data
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: www-data
        hostPath:
          path: /var/www/html
