apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: my-www
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: www
    nodePort: 30080
  - port: 443
    protocol: TCP
    targetPort: 443
    name: ssl
    nodePort: 30443
  selector:
    app: www
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
