apiVersion: v1
kind: Pod
metadata:
  name: www
  labels: 
    name: www
spec: 
  containers: 
    - image: myhttpdssl
      name: myhttpdssl
      ports: 
        - containerPort: 80
          name: httpd
          hostPort: 80
        - containerPort: 443
          name: ssl
          hostPort: 443
      volumeMounts:
        - name: www-data
          mountPath: /usr/local/apache2/htdocs/
  volumes:
    - 
     name: www-data
     hostPath: 
      path: /var/www/html

